### ISSUE TITLE
很棒啊！

### ISSUE THREAD

**Issue by criwits** [Wenti-D/YetAnotherMusicPlayer#1]
~~哼！哼哼！嗯啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊~~
Windy 还是 Windy 啊！我就靠着你的播放器来入门 Python 了。
---
正经一点，先提一个 Issue：README 文件中，“编译”说法不准确。Python 作为解释型语言应该叫“运行”而不是“编译”。

**Comment by Wenti-D** [comment]
吼！
~~禁止随地恶臭~~
